CREATE TABLE kanban.responsibles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (length(trim(name)) > 0),
    email VARCHAR(254) NOT NULL CHECK (email = lower(trim(email)) AND length(email) > 0),
    role VARCHAR(120) NOT NULL CHECK (length(trim(role)) > 0),
    department VARCHAR(120) NOT NULL CHECK (length(trim(department)) > 0),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT "responsibleEmailUnique" UNIQUE (email)
);
