CREATE TABLE kanban.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (length(trim(name)) > 0),
    "plannedStartDate" DATE,
    "plannedEndDate" DATE,
    "actualStartDate" DATE,
    "actualEndDate" DATE,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT "plannedDateOrder" CHECK ("plannedEndDate" >= "plannedStartDate"),
    CONSTRAINT "actualDateOrder" CHECK ("actualEndDate" >= "actualStartDate")
);

CREATE TABLE kanban."projectResponsibles" (
    "projectId" BIGINT NOT NULL REFERENCES kanban.projects (id) ON DELETE CASCADE,
    "responsibleId" BIGINT NOT NULL,
    PRIMARY KEY ("projectId", "responsibleId"),
    CONSTRAINT "projectResponsibleResponsibleFk"
        FOREIGN KEY ("responsibleId") REFERENCES kanban.responsibles (id) ON DELETE RESTRICT
);

CREATE INDEX "projectResponsiblesByResponsible" ON kanban."projectResponsibles" ("responsibleId");
