CREATE TABLE kanban.departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (length(trim(name)) > 0),
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT "departmentNameReferenceUnique" UNIQUE (name)
);

CREATE UNIQUE INDEX "departmentNameUnique" ON kanban.departments (lower(name));

INSERT INTO kanban.departments (name, "createdAt", "updatedAt")
SELECT DISTINCT department, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM kanban.responsibles;

ALTER TABLE kanban.responsibles
    ADD CONSTRAINT "responsibleDepartmentFk"
    FOREIGN KEY (department) REFERENCES kanban.departments (name)
    ON UPDATE CASCADE ON DELETE RESTRICT;
